# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:        
    - name: Notify Slack
      uses: ravsamhq/notify-slack-action@v1
      if: github.event.pull_request.merged
      with:
        status: ${{ job.status }}
        notification_title: '{workflow} has {status_message}'
        message_format: '${{ github.event.head_commit.message }}'

        footer: 'Linked Repo <{repo_url}|{repo}>'
        notify_when: 'failure, success'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
